<a href="https://colab.research.google.com/github/jangidprashantjee185045/ann/blob/project1/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch

In [21]:
import torch
import numpy as np

In [3]:
t=torch.tensor([1,2,3,4,5,6])
print(t)

tensor([1, 2, 3, 4, 5, 6])


In [4]:
print(t[1:4])

tensor([2, 3, 4])


In [5]:
print(t[:2])

tensor([1, 2])


In [6]:
print(t[1:])

tensor([2, 3, 4, 5, 6])


In [17]:
f=torch.FloatTensor([1,2,3,4,6,6])

In [18]:
print(f)

tensor([1., 2., 3., 4., 6., 6.])


In [9]:
print(f.dtype)

torch.float32


In [11]:
print(f.size())

torch.Size([7])


In [12]:
f.view(7,1) 

tensor([[1.],
        [2.],
        [3.],
        [3.],
        [4.],
        [6.],
        [6.]])

In [19]:
f.view(3,2) #no. of elements should be same

tensor([[1., 2.],
        [3., 4.],
        [6., 6.]])

In [20]:
f.view(3,-1)

tensor([[1., 2.],
        [3., 4.],
        [6., 6.]])

In [22]:
a=np.array([1,2,3,4,5,6])

In [23]:
print(a)

[1 2 3 4 5 6]


In [25]:
cnt=torch.from_numpy(a)

In [26]:
cnt

tensor([1, 2, 3, 4, 5, 6])

In [29]:
cnp=cnt.numpy()

In [30]:
cnp

array([1, 2, 3, 4, 5, 6])